name: Demo1
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  call-workflow1:
    uses: ./.github/workflows/workflow1.yaml
  call-workflow2:
    if: ${{ always() }} #This will make your workflow2 executed even if workflow1 fails, remove this, if you want to run this only on success of workflow1
    needs: call-workflow1
    uses: ./.github/workflows/workflow2.yaml
