name: Job1
on:
  workflow_run:
    workflows: [Job2]
    types:
      - completed
jobs:
  builyd:
    runs-on: ubuntu-lates
    steps:
      - name: Run a one-line script
        run: echo Job1 Executed!
